# Generated by Django 3.2.6 on 2022-06-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=8)),
                ('ProductName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
